dist: trusty  
language: cpp
git:
  depth: false
matrix:
  include:
    - name: Linux GCC
      compiler: gcc
      os: linux
      script:
        - make -f test/Makefile
        - test/test
    - name: macOS
      compiler: clang
      os: osx
      osx_image: xcode7.3
      script:
        - make -f test/Makefile
        - test/test