version: 2
workflows:
  version: 2
  dist-compile:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: make -f test/Makefile
      - run: test/test
